a=input("digite algo\n")
print("o tipo da variavel é:",type(a))
print("só tem espaços:", a.isspace())
print("é um numero?", a.isnumeric())
print("é uma letra?", a.isalpha())
print("é um numero e letra?", a.isalnum())
print("esta em maiuscula?", a.isupper())
print("esta em minusculo?", a.islower())
print("esta capitalizada?", a.istitle())
